package ${entity.javaPackage};

/**
* This code is generated by FreeMarker
*
*/
public class ${entity.className}<#if entity.superclass?has_content> extends ${entity.superclass} </#if>
{
/********** attribute ***********/
<#list entity.properties as property>
    public ${property.javaType} ${property.propertyName};

</#list>
/********** constructors ***********/
<#if entity.constructors>
    public ${entity.className}() {

    }

    public ${entity.className}(<#list entity.properties as property>${property.javaType} ${property.propertyName}<#if property_has_next>, </#if></#list>) {
    <#list entity.properties as property>
        this.${property.propertyName} = ${property.propertyName};
    </#list>
    }
</#if>

    @Override
    public String toString() {
        return "${entity.className}{" +
            <#list entity.properties as property>
                "${property.propertyName}="+${property.propertyName}<#if property_has_next>+"," </#if>+
            </#list>
            '}';
    }

}