package com.yzx.entity;

    import com.yzx.entity.User;
import java.util.*;

/**
* This code is generated by FreeMarker
*
*/
public class ListTest
{
/********** attribute ***********/
    public List<User> users  = new ArrayList<>();

    public int cnt ;

/********** constructors ***********/
    public ListTest() {

    }

    public ListTest(List<User> users, int cnt) {
        this.users = users;
        this.cnt = cnt;
    }

    @Override
    public String toString() {
        return "ListTest{" +
                "users="+users+"," +
                "cnt="+cnt+
            '}';
    }

    public String toCSVString(){
        return users+","+cnt;
    }

}
