package com.yzx.entity;

import java.util.*;

/**
* This code is generated by FreeMarker
*
*/
public class User
{
/********** attribute ***********/
    public String name ;

    public int age ;

/********** constructors ***********/
    public User() {

    }

    public User(String name, int age) {
        this.name = name;
        this.age = age;
    }

    @Override
    public String toString() {
        return "User{" +
                "name="+name+"," +
                "age="+age+
            '}';
    }

    public String toCSVString(){
        return name+","+age;
    }

}
